name: Docker CI/CD Script

on:
  pull_request:
    branches:
      - master
      - desarrollo
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Loguea en Docker Hub
      #- name: Docker login
      #  env:
      #    DOCKER_USER: ${{ secrets.DOCKER_USER }}
      #    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #  run: |
      #    docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
        
      - name: Get Hash
        id: hash
        run: echo "git_hash=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_HASH

      - name: Check Hash
        run: echo "${{ env.hash }}"
        
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./docker
          push: true
          tags: |
            docker.pkg.github.com/${{ github.repository }}/hola-mundo:${{ steps.extract_branch.outputs.branch }} ${{ env.branch }} ${{ env.hash }}
            docker.pkg.github.com/${{ github.repository }}/hola-mundo:${{ steps.extract_branch.outputs.branch }} ${{ env.branch }} ${{ env.hash }}
          
      # Contruye la imagen 
      #- name: Docker build
      #  run: |
      #    docker build ./docker -t francironee/hola-mundo:${{ steps.extract_branch.outputs.branch }}
          
     
        
      # La pushea hacia Docker Hub 
      #- name: Docker push
      #  run: |
      #    docker.pkg.github.com/${{ github.repository }}/hola-mundo:${{ steps.extract_branch.outputs.branch }}
      #     docker.pkg.github.com/${{ github.repository }}/hola-mundo:${{ steps.extract_branch.outputs.branch }}

          
      
