name: Docker CI/CD Script

# Cuando se van a ejecutar las tareas
on:
  pull_request:
    branches:
      - master
      - desarrollo
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    # Secuencia de tareas que se van a ejecutar
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Loguea en Docker Hub
      - name: Docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          
      # Contruye la imagen 
      - name: Docker build
        run: |
          docker build ./docker -t francironee/hola-mundo:prod
          
      # La pushea hacia Docker Hub 
      - name: Docker push
        run: |
          docker push francironee/hola-mundo:prod
          
      
