name: Testing

on:
  pull_request:
    branches: 
      - master
      - desarrollo
    types: [opened]

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:   
      - uses: actions/checkout@v3
      
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - run: npm ci
        working-directory: ./docker
      - run: npm run build --if-present
        working-directory: ./docker
      - run: npm test
        working-directory: ./docker
