name: Testing

on:
  pull_request:
    branches: 
      - master
      - desarrollo

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:   
      - uses: actions/checkout@v3
      
      
      - name: npm test
        run: npm test
        env:
          GITHUB_TOKEN: ${{ github.token }}
